### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [srebughini/JASALI#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by srebughini** [comment]
Hey,

thank you for your idea. Sure, I don't know how to do something like this, so your contribution is very welcome 👍

**Comment by geopic** [comment]
Excellent. You don't need to do much, just check if the data types are correct in my PR :smile:
